dataset:
    #name: mu_KNO_Type3_20cov_100Mev
    name: /positron_.*/
    #name: /positron_10MeV/
    split: [0.7, 0.2] ## training set, validation set
random:
    seed: 12345
    shuffle: True
    gpu-deterministic: False
training:
    epoch: 500
    batch: 32
    learningRate: 1e-5
model:
    name: PerceiverIO
    dLatent: 128
    nHead: 128
    dHead: 128
    nLayers: 5
    dropout: 0.1
        
