dataset:
    #name: mu_KNO_Type3_20cov_100Mev
    name: /positron_.*/
    split: [0.7, 0.2] ## training set, validation set
random:
    seed: 12345
    shuffle: True
    gpu-deterministic: False
training:
    epoch: 500
    batch: 32
    learningRate: 1e-3
model:
    name: Basic
        
